# Generated by Django 2.2.5 on 2019-10-03 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0002_auto_20191003_1518'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='blogname',
            new_name='blog_name',
        ),
    ]
