# Generated by Django 2.2.5 on 2019-10-11 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20191010_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_icon',
            field=models.ImageField(blank=True, null=True, upload_to='profile_icons', verbose_name='アイコン'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='self_introduction',
            field=models.CharField(blank=True, max_length=512, verbose_name='自己紹介'),
        ),
    ]
