# Generated by Django 2.2.5 on 2019-10-15 00:55

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20191011_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_icon',
            field=stdimage.models.StdImageField(blank=True, null=True, upload_to='profile_icons/', verbose_name='アイコン'),
        ),
    ]
