# Generated by Django 2.2.5 on 2019-10-18 00:32

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20191015_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_icon',
            field=stdimage.models.StdImageField(default='default.png', upload_to='profile_icons/', verbose_name='アイコン'),
        ),
    ]
