# Generated by Django 2.2.5 on 2019-11-08 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20191018_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='self_introduction',
            field=models.CharField(blank=True, max_length=150, verbose_name='自己紹介'),
        ),
    ]
