# Generated by Django 2.2.5 on 2019-10-02 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20191002_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='image.png', null=True, upload_to='media/pitures'),
        ),
    ]
