# Generated by Django 2.2.5 on 2019-10-02 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20191002_1721'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='updated_by_id',
        ),
    ]
