# Generated by Django 2.2.5 on 2019-10-03 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20191003_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='blog_id',
            field=models.IntegerField(default=0),
        ),
    ]
