# Generated by Django 2.2.5 on 2019-10-08 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20191008_0924'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category_id',
            field=models.IntegerField(default=0),
        ),
    ]
