# Generated by Django 2.2.5 on 2019-10-16 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20191015_0955'),
        ('blog', '0015_auto_20191016_1419'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='blog_id',
        ),
        migrations.AddField(
            model_name='category',
            name='blog',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='accounts.Blog', verbose_name='掲載ブログ'),
        ),
    ]
