# Generated by Django 2.2.5 on 2019-10-25 04:45

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfile',
            name='file',
            field=stdimage.models.StdImageField(blank=True, null=True, upload_to='pictures/'),
        ),
    ]
