# Generated by Django 2.2.5 on 2019-10-25 05:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0004_auto_20191025_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfile',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
