# Generated by Django 2.2.5 on 2019-11-05 02:54

from django.db import migrations, models
import django.db.models.deletion
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_auto_20191018_0932'),
        ('image', '0005_auto_20191025_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadfile',
            name='post',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='blog.Post'),
        ),
        migrations.AlterField(
            model_name='uploadfile',
            name='file',
            field=stdimage.models.StdImageField(upload_to='pictures/'),
        ),
    ]
