# Generated by Django 2.2.5 on 2019-11-05 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0008_auto_20191105_1155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadfile',
            name='post',
        ),
    ]
