# Generated by Django 2.2.5 on 2019-10-01 04:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommentForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('artilcle_id', models.IntegerField()),
                ('created_date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
