# Generated by Django 2.2.5 on 2019-10-01 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CommentForm',
            new_name='Comment',
        ),
    ]
