# Generated by Django 2.2.5 on 2019-10-01 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_auto_20191001_1418'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='artilcle_id',
            new_name='article_id',
        ),
    ]
