# Generated by Django 2.2.5 on 2019-10-18 01:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0004_comment_blog_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='blog_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='blog.Post', verbose_name='元記事'),
        ),
    ]
