# Generated by Django 2.2.5 on 2019-10-18 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0007_auto_20191018_1015'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='article_id',
            new_name='article',
        ),
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.CharField(default='名無しさん', max_length=200),
        ),
    ]
